"""empty message

Revision ID: 97f27bc97c9a
Revises: 3c19b223bc0d
Create Date: 2020-02-20 23:46:08.740138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f27bc97c9a'
down_revision = '3c19b223bc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('one', sa.Integer(), nullable=True),
    sa.Column('two', sa.Integer(), nullable=True),
    sa.Column('three', sa.Integer(), nullable=True),
    sa.Column('four', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('one', sa.Integer(), nullable=True),
    sa.Column('two', sa.Integer(), nullable=True),
    sa.Column('three', sa.Integer(), nullable=True),
    sa.Column('four', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('one', sa.Integer(), nullable=True),
    sa.Column('two', sa.Integer(), nullable=True),
    sa.Column('three', sa.Integer(), nullable=True),
    sa.Column('four', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdp')
    op.drop_table('library')
    op.drop_table('college')
    # ### end Alembic commands ###
